production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGOLAB_URI'] %>
      options:
        connect_timeout: 30
        wait_queue_timeout: 30
  options:
     log_level: :fatal
development:
  clients:
    default:
      uri: mongodb://localhost:27017/massr
  options:
     log_level: :info
test:
  clients:
    default:
      uri: mongodb://localhost:27017/massr_test
  options:
     log_level: :info
